version: '3.8'

services:

  database:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: sem_1
      PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes: .:/var/lib/postgresql/data

  sem_1:
    build: ../..
    container_name: sem-service
    depends_on:
      - database
    links:
      - database
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres


networks:
  backend:
    driver: bridge





